# roles/tomcat/vars/main.yml
---

tomcat_packages:
  - tomcat9

tomcat_admin_packages:
  - tomcat9-admin

tomcat_service: tomcat9
tomcat_user: tomcat

# Directories
tomcat_home_dir: /usr/share/tomcat
tomcat_lib_dir: /usr/share/java/tomcat
tomcat_app_dir: /var/lib/tomcat/webapps


