# Generated by Django 2.2 on 2020-06-26 13:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=63)),
                ('email', models.EmailField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Articol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=63)),
                ('continut_articol', models.TextField()),
                ('data_adaugarii', models.DateTimeField(default=datetime.datetime(2020, 6, 26, 13, 10, 1, 682986, tzinfo=utc))),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicatie.Autor')),
            ],
        ),
    ]
