# Generated by Django 2.2 on 2020-06-26 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articol',
            name='imagine',
            field=models.ImageField(default='static/default_img.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='articol',
            name='data_adaugarii',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
